version : "3.3"

services:
  sourceswitcher:
    image: medcelerate/brave:latest
    volumes:
      - brave:/usr/local/share/brave
    networks:
      main:
        aliases:
          - sourceswitcher


  rtmpproxy:
    image: medcelerate/serg-nginx-rtmp:1cdd825
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./conf/nginx_http.conf:/etc/nginx/conf.d/nginx_http.conf
      - ./conf/nginx_rtmp.conf:/etc/nginx/conf.d/rtmp/nginx_rtmp.conf
      - nginx:/tmp/hls
      #- ./hls:/var/hls #Edit this to point to where your hls files should be written for your web server.
    networks:
      main:
        aliases:
          - rtmpproxy
networks:
    main:

volumes:
  brave:
  nginx: