version : "3.3"

services:
  sourceswitcher:
    image: medcelerate/brave:latest
    volumes:
      - brave:/usr/local/share/brave
    networks:
      main:
        aliases:
          - sourceswitcher


  rtmpproxy:
    image: ossrs/srs:3
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./conf/srs.conf:/usr/local/srs/conf/srs.conf
      - ./srs.log:/usr/local/srs/objs/srs.log
      - nginx:/tmp/hls
      #- ./hls:/var/hls #Edit this to point to where your hls files should be written for your web server.
    networks:
      main:
        aliases:
          - rtmpproxy
networks:
    main:

volumes:
  brave:
  nginx: